# frozen_string_literal: true

source 'https://rubygems.org'

gem 'filemagic'
gem 'ruby-debug-ide'
gem 'sinatra', '~> 1.4'
gem 'sqlite3'
gem 'string_to_id'

group :development do
  gem 'rubocop', '~> 1.66'
end
